# Generated by Django 4.0.4 on 2022-05-07 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ak_company', '0003_friendship_userprofil_friends_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 10, 39, 54, 132541, tzinfo=utc)),
        ),
    ]
