# Generated by Django 3.2.5 on 2022-05-08 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ak_company', '0005_auto_20220507_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='product_id',
            field=models.AutoField(default=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofil',
            name='coordinat_sekarang',
            field=models.CharField(default=3, max_length=10000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofil',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('M', 'makanan'), ('P', 'pakaian'), ('A', 'aksesoris'), ('SB', 'sayur dan buah - buahan'), ('ART', 'alat rumah tangga')], max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('H', 'hot'), ('T', 'terbaru'), ('P', 'populer')], max_length=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 6, 30, 57, 218747, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='fotoktp_mitra_company',
            field=models.ImageField(default=None, upload_to='images/profil/mitra/ktp/'),
        ),
        migrations.CreateModel(
            name='transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ak_company.item')),
                ('username_transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ak_company.userprofil')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ak_company.item')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ak_company.userprofil')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='ak_company.OrderItem')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ak_company.userprofil')),
            ],
        ),
        migrations.CreateModel(
            name='imageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/product/')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ak_company.item')),
            ],
        ),
        migrations.CreateModel(
            name='favorit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorit_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ak_company.item')),
                ('username_favorit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ak_company.userprofil')),
            ],
        ),
    ]
