# Generated by Django 3.2.5 on 2022-05-09 06:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ak_company', '0006_auto_20220508_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 6, 23, 17, 857823, tzinfo=utc)),
        ),
    ]
