# Generated by Django 3.2.5 on 2022-05-09 11:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ak_company', '0007_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproduct',
            name='image1',
            field=models.ImageField(default=3, upload_to='images/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='image2',
            field=models.ImageField(default=3, upload_to='images/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='image3',
            field=models.ImageField(default=3, upload_to='images/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='image4',
            field=models.ImageField(default=3, upload_to='images/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='image5',
            field=models.ImageField(default=3, upload_to='images/product/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 11, 37, 35, 436544, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='Receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toMessageUser', to='ak_company.userprofil'),
        ),
        migrations.AlterField(
            model_name='message',
            name='Sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofMessageUser', to='ak_company.userprofil'),
        ),
    ]
